# Generated by Django 5.2.1 on 2025-05-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='books/image/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='books/pdfs/'),
        ),
    ]
