# Generated by Django 5.2.1 on 2025-05-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyrap', '0002_book_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingrecord',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Declined'), (2, 'Approved')], default=0),
        ),
    ]
